model_list:
  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: ${GOOGLE_API_KEY}

litellm_settings:
  drop_params: true
  request_timeout: 30
  verbose: true